### ISSUE TITLE
PlayerEx: Director's Cut v3.6.1, MC v1.20.1 - Ranged Damage Not Displaying Properly After Archers (RPG Series) Update

### ISSUE THREAD

**Issue by rxay579** [PlayerEXDirectorsCut/playerex#10]
PlayerEx: Director's Cut v3.6.1, MC v1.20.1, Archer (RPG Series) v1.2.1.
Custom mod list.  Full list available in latest.log (attached).
[latest.log](https://github.com/PlayerEXDirectorsCut/playerex/files/15161124/latest.log)

The mod list was originally put together mid March with Archers v1.0.7 and no issues were noted at that time.
After a relatively recent update to the Archers mod, the Ranged Damage attribute in the Combat tab doesn't appear to be displaying properly.
This happens in single player and when connecting to a local server.
I think this may be related to the Archers mod switching to RangedWeaponAPI with their v 1.1.0, but I'm not sure.
https://modrinth.com/mod/archers/changelog

**Comment by MerryweatherLost** [comment]
Thanks for bringing this to our attention, it will be resolved in the upcoming update.
