### ISSUE TITLE
[FEATURE] Item Breaking Mechanics

### ISSUE THREAD

**Issue by pokesmells** [PlayerEXDirectorsCut/playerex#25]
- Items will `not break`, but rather `be broken`, which will be `indicated via tooltip` and also the item will be `grayed out`, making it unusable until it is repaired `via the anvil`. 

- If you have mending, this can also work by slowly repairing the item, thus making `it usable over time`. Might add **repair kits** to use on **armor/tools** as well.

**Comment by naomieow** [comment]
TODO:
- [x] Broken armour doesn't supply armour points
- [x] Broken tooltip
- [x] Dimmed texture when broken
- [x] BetterCombat compat (low prio)
