### ISSUE TITLE
[Compat Issue] Levelz overlaying over Playerx menus

### ISSUE THREAD

**Issue by TheShadyyOneYT** [PlayerEXDirectorsCut/playerex#40]
What the issue looks like: https://imgur.com/a/KNe3ks2

Levelz menus overlap over PlayerEx menus in the inventory.

Versions:
PlayerEx Mod version: 3.7.3
Modloader Version: 0.16.0
Fabric Api Version: 0.92.2
Game Version: 1.20.1
Levelz: 1.4.13
Jobs Addon (For levelz): 1.1.6

**Comment by pokesmells** [comment]
We will not fix bugs for the old release version, for now you may use the latest alpha including the latest alphas for Data Attributes, WizardEx, and RelicEx. The new keybind on the new menu is `-`.
