### ISSUE TITLE
On death player loses level and stats (with reset on death set to disabled)

### ISSUE THREAD

**Issue by Raiiiden** [PlayerEXDirectorsCut/playerex#41]
Forge 47.3.0
https://mclo.gs/ifSvTcd
![Screenshot (3207)](https://github.com/user-attachments/assets/c5d90fa4-4b6d-4a44-9458-788f8c31e5fd)

**Comment by Raiiiden** [comment]
This is using Sinytra Connector

**Comment by Raiiiden** [comment]
On death it doesn't reset unused skill points, just level and assigned points/stats

**Comment by cassie-jfs** [comment]
Should be fixed in beta.4
