### ISSUE TITLE
[Bug] Crash when clicking to change from add to multiply in attribute functions in in-game config [Fabric 0.16.02/1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [PlayerEXDirectorsCut/playerex#46]
### What happened? Describe in detail down below and include the mod version as well.

https://mclo.gs/wRCYnuQ

Crash

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [ ] Visual
- [ ] Feature Related
- [X] Crash
- [ ] Mod Conflict
- [ ] Others

### Relevant logs

```shell
https://mclo.gs/wRCYnuQ
```

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by cassie-jfs** [comment]
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
flipping config needs triage and fixes
