### ISSUE TITLE
Point Allocation Count Incorrect

### ISSUE THREAD

**Issue by LightningFerix** [PlayerEXDirectorsCut/playerex#47]
### What happened? Describe in detail down below and include the mod version as well.

When I increase my stats, the point allocation value increases by more than 1. Like when I click the + button once, I'd expect my score for Intelligence to go up by 1, but it goes up by more. This is problematic because there is a cap of 100 points allocatable and I’ll cap out without actually having allocated 100 points. 

Could this be an unintentional two-way association between the value representing how many points I've allocated to a stat and the actual value of the stat? Because some other mods that I have including RelicEx and Simply Skills that increase my specific stats either through a direct bonus or a percentage increase, the actual value of a stat might not increase linearly relative to the allocated points value,so instead of showing the actual number of points allocated into INT, it's showing me how many points I would have allocated to be able to have the actual INT value I currently have through RelicEx and Simply Skills. Sorry for the rambling, just curious. 

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [ ] Visual
- [X] Feature Related
- [ ] Crash
- [ ] Mod Conflict
- [ ] Others

### Relevant logs

```shell
N/A
```

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by cassie-jfs** [comment]
I'll look towards investigating the issue soon when I'm not busy, thanks for reporting

**Comment by cassie-jfs** [comment]
Ah I see, well the allocations are tied to the attributes directly, which is probably why you are having this issue. I could plan on making those allocatable entries separate from the actual attribute value, though I'll need to devise a plan on the backend and front-end for this. Thanks for reporting this, I'll see about a solution in the future.

**Comment by cassie-jfs** [comment]
See #48 for any updates on this in the future

**Comment by cassie-jfs** [comment]
This was integrated into the beta channel some time ago, forgot to close!
