### ISSUE TITLE
Client desync when returning to inventory tab from playerex tab/s

### ISSUE THREAD

**Issue by deskydesqui** [PlayerEXDirectorsCut/playerex#5]
Currently using PlayerEX: Directors Cut 3.6.0

How to replicate:

Have block in hand
Open Inventory
Switch to any playerex tab
Return to inventory, and place block in a different slot
Right click to place desynced block

**Comment by MerryweatherLost** [comment]
Hello, I'm looking into replicating and solving this, thanks for reporting.

**Comment by MerryweatherLost** [comment]
This problem has been solved, thanks again for reporting this issue.
The Curseforge and Modrinth pages should be updated soon, give them an hour or two to get approval and upload, thanks!

See PR: #6

**Comment by deskydesqui** [comment]
Awesome, update works great. Thanks for the port!

**Comment by pokesmells** [comment]
> Awesome, update works great. Thanks for the port!

Anytime! Please let us know anytime there is an issue 🙏🏽 Have a great day
