### ISSUE TITLE
[Bug] DataAttributes version check fails

### ISSUE THREAD

**Issue by Derpford** [PlayerEXDirectorsCut/playerex#54]
### What happened? Describe in detail down below and include the mod version as well.

On Fabric 1.20.1, PlayerEX DC looks for DataAttributes Director's Cut version 1.5.2 or later. I have version 2.0.2 installed, but the mods fail to launch, claiming that no compatible version of dataattributes_dc is present.

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [ ] Visual
- [ ] Feature Related
- [ ] Crash
- [ ] Mod Conflict
- [X] Others

### Relevant logs

```shell
See attached log.
```

### Anything else?

[latest.log](https://github.com/user-attachments/files/17796620/latest.log)

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by pokesmells** [comment]
What's the version of PlayerEx

**Comment by pokesmells** [comment]
PlayerEx is in beta, so latest release may not be downloaded

**Comment by Derpford** [comment]
According to the log, I was apparently using PlayerEXDC version 3.7.3, while the latest available beta is version 4.0.0! I should've double checked before assuming Curseforge would install the latest available version.

V4.0.0 appears to work just fine, so I'll close this issue. Thanks for your patience.
