### ISSUE TITLE
[Bug] Crash When Load World With Improved Mobs

### ISSUE THREAD

**Issue by CaoTrongThang** [PlayerEXDirectorsCut/playerex#55]
### What happened? Describe in detail down below and include the mod version as well.

I installed this mod and just create a new world, then the world crashed, don't know what mod is conflicting with the mod.

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [ ] Visual
- [ ] Feature Related
- [X] Crash
- [ ] Mod Conflict
- [ ] Others

### Relevant logs

```shell
Crash log: https://mclo.gs/eYa10AZ
```

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by pokesmells** [comment]
What version of playerex are you using

**Comment by pokesmells** [comment]
nvm I see the issue is a conflict with Improved mobs, please make a report to them as well

**Comment by DataEncoded** [comment]
seems like the issue with this is that improved mobs attempts to use the api of the old playerex, meanwhile our api is slightly different

**Comment by CaoTrongThang** [comment]
Should i close the issue?, or i can let it here for people to aware.

**Comment by pokesmells** [comment]
> Should i close the issue?, or i can let it here for people to aware.

We'll keep it open for now, but please make sure to report it to them as well

**Comment by pokesmells** [comment]
This has been resolved by the author
