### ISSUE TITLE
[Bug] Crit chance values and damage not matching

### ISSUE THREAD

**Issue by Kribys407** [PlayerEXDirectorsCut/playerex#62]
### What happened? Describe in detail down below and include the mod version as well.

PlayerEx crit damage, while set to 40%, is increasing damage by around 500% in some cases.

Steps taken for replication:
Take weapon
Strength 100, Luck 20
Begin whacking
Observe damage
(In cases where an item would be doing 12 it is doing 60, some cases 

### What mod loaders is this problem occuring on?

Fabric

### What do you think this bug is related to?

- [ ] Visual
- [x] Feature Related
- [ ] Crash
- [ ] Mod Conflict
- [ ] Others

### Relevant logs

```shell
https://mclo.gs/fZKvMyj
```

### By submitting this issue, I have confirmed I have followed all instructions and all my mods are up-to-date.

- [X] Yes

**Comment by DataEncoded** [comment]
fixed thank you for the report!
